---
create_user: "metis" 
copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
sys_packages: [ 'curl', 'vim', 'git', 'ufw', 'fail2ban']
influx_db: ""
influx_username: ""
influx_password: ""
influx_endpoint: "http://:8086"
